Repository code0-tech/sagittarius, pull requests merged in 2024-05, with the labels that each got.

#146 add some test cases for audit events
  spec/services/users/login_service_spec.rb
Labels: enhancement

#156 implement administrator ability with all other abilities in the customizable_permission system
  app/models/organization_role_ability.rb
  app/policies/concerns/customizable_permission.rb
  app/policies/organization_policy.rb
  app/services/organizations/create_service.rb
  docs/content/graphql/enum/organizationroleability.md
  spec/policies/concerns/customizable_permission_spec.rb
  spec/services/organizations/create_service_spec.rb
Labels: enhancement

#162 Improve pipeline summaries
  .gitlab-ci.yml
Labels: tooling

#164 Add prevention for deleting/removing last user from admin role
  app/services/organization_members/assign_roles_service.rb
  app/services/organization_members/delete_service.rb
  spec/requests/graphql/mutation/organization_members/assign_roles_mutation_spec.rb
  spec/requests/graphql/mutation/organization_members/delete_mutation_spec.rb
  spec/services/organization_members/assign_roles_service_spec.rb
  spec/services/organization_members/delete_service_spec.rb
Labels: enhancement

#154 Create 'organization_licenses' table and corresponding models
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/graphql/types/mutation_type.rb
  app/models/audit_event.rb
  app/models/organization.rb
  app/models/organization_role_ability.rb
  app/policies/organization_policy.rb
  config/initializers/license.rb
  config/keys/license_encryption_key_development.pub
  config/keys/license_encryption_key_production.pub
  db/migrate/20240428201726_create_organization_licenses.rb
  db/schema_migrations/20240428201726
  db/structure.sql
  docs/content/graphql/enum/organizationroleability.md
  docs/content/graphql/mutation/organizationlicensescreate.md
  docs/content/graphql/object/organizationlicense.md
  docs/content/graphql/scalar/organizationlicenseid.md
  ee/app/graphql/ee/types/mutation_type.rb
  ee/app/graphql/mutations/organization_licenses/create.rb
  ee/app/graphql/types/organization_license_type.rb
  ee/app/models/ee/organization.rb
  ee/app/models/organization_license.rb
  ee/app/policies/ee/organization_policy.rb
  ee/app/policies/organization_license_policy.rb
  ee/app/services/organization_licenses/create_service.rb
  ee/spec/factories/organization_licenses.rb
  ee/spec/graphql/mutations/organization_licenses/create_spec.rb
  ee/spec/graphql/types/ee/types/mutation_type_spec.rb
  ee/spec/graphql/types/organization_license_type_spec.rb
  ee/spec/models/ee/organization_spec.rb
  ee/spec/models/organization_license_spec.rb
  ee/spec/policies/ee/organization_policy_spec.rb
  ee/spec/requests/graphql/mutations/organization_licenses/create_mutation_spec.rb
  ee/spec/services/organization_licenses/create_service_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#170 Support extended type in GraphQL field matcher
  spec/support/matchers/graphql_matchers.rb
Labels: enhancement

#163 Prevent removing organization administrator ability from all roles
  app/services/organization_roles/assign_abilities_service.rb
  app/services/organization_roles/delete_service.rb
  spec/requests/graphql/mutation/organization_roles/assign_abilities_mutation_spec.rb
  spec/requests/graphql/mutation/organization_roles/delete_mutation_spec.rb
  spec/services/organization_roles/assign_abilities_service_spec.rb
  spec/services/organization_roles/delete_service_spec.rb
Labels: enhancement

#171 Implement query for licenses
  app/graphql/types/organization_type.rb
  docs/content/graphql/object/organization.md
  docs/content/graphql/object/organizationlicenseconnection.md
  docs/content/graphql/object/organizationlicenseedge.md
  ee/app/graphql/ee/types/organization_type.rb
  ee/spec/graphql/types/ee/types/organization_type_spec.rb
  spec/graphql/types/organization_type_spec.rb
Labels: enhancement

#174 Create organization projects and create mutation
  app/graphql/mutations/organization_projects/create.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/organization_project_type.rb
  app/models/audit_event.rb
  app/models/organization.rb
  app/models/organization_project.rb
  app/models/organization_role_ability.rb
  app/policies/organization_policy.rb
  app/policies/organization_project_policy.rb
  app/services/organization_projects/create_service.rb
  db/migrate/20240511130911_create_organization_projects.rb
  db/schema_migrations/20240511130911
  db/structure.sql
  docs/content/graphql/enum/organizationroleability.md
  docs/content/graphql/mutation/organizationprojectscreate.md
  docs/content/graphql/object/organizationproject.md
  docs/content/graphql/scalar/organizationprojectid.md
  spec/factories/organization_projects.rb
  spec/graphql/mutations/organization_projects/create_spec.rb
  spec/graphql/types/organization_project_type_spec.rb
  spec/models/organization_project_spec.rb
  spec/policies/organization_project_policy_spec.rb
  spec/requests/graphql/mutation/organization_projects/create_mutation_spec.rb
  spec/services/organization_projects/create_service_spec.rb
Labels: enhancement

#177 Implement UserAbilities type helper
  app/graphql/sagittarius_schema.rb
  app/graphql/types/base_object.rb
  spec/support/matchers/graphql_matchers.rb
Labels: enhancement

#184 only save extensions when a list isn't empty
  config/initializers/0_inject_extensions.rb
Labels: bug

#182 add query for organization projects
  app/graphql/types/organization_type.rb
  docs/content/graphql/object/organization.md
  docs/content/graphql/object/organizationprojectconnection.md
  docs/content/graphql/object/organizationprojectedge.md
  ee/spec/graphql/types/ee/types/organization_type_spec.rb
  spec/graphql/types/organization_type_spec.rb
Labels: enhancement

#169 Remove license mutation
  app/models/audit_event.rb
  app/models/organization_role_ability.rb
  docs/content/graphql/enum/organizationroleability.md
  docs/content/graphql/mutation/organizationlicensesdelete.md
  ee/app/graphql/ee/types/mutation_type.rb
  ee/app/graphql/mutations/organization_licenses/delete.rb
  ee/app/services/organization_licenses/delete_service.rb
  ee/spec/requests/graphql/mutations/organization_licenses/delete_mutation_spec.rb
  ee/spec/services/organization_licenses/delete_service_spec.rb
Labels: enhancement

#189 License loading
  ee/app/models/organization_license.rb
  ee/spec/models/organization_license_spec.rb
  lib/sagittarius/memoize.rb
  spec/lib/sagittarius/memoize_spec.rb
Labels: enhancement

#193 Migrate to new build image name
  .gitlab-ci.yml
Labels: tooling

#192 Enforce user limit
  Gemfile
  Gemfile.lock
  app/services/organization_members/invite_service.rb
  ee/app/models/ee/organization.rb
  ee/app/models/organization_license.rb
  ee/app/services/ee/organization_members/invite_service.rb
  ee/spec/factories/organization_licenses.rb
  ee/spec/services/ee/organization_members/invite_service_spec.rb
Labels: enhancement
