Repository code0-tech/sagittarius, pull requests merged in 2024-08, with the labels that each got.

#257 Disable Metrics cops globally
  .rubocop.yml
  app/controllers/graphql_controller.rb
  app/graphql/types/global_id_type.rb
  app/services/namespace_members/assign_roles_service.rb
  app/services/namespace_roles/assign_projects_service.rb
  lib/sagittarius/database/migration_helpers/table_enhancements.rb
  spec/support/helpers/graphql_helpers.rb
  spec/support/matchers/graphql_matchers.rb
  tooling/graphql/docs/helper.rb
Labels: enhancement, tooling

#259 Now we are actually using traits instead of the raw admin value
  spec/requests/graphql/mutation/runtimes/create_mutation_spec.rb
  spec/requests/graphql/mutation/runtimes/delete_mutation_spec.rb
  spec/requests/graphql/mutation/runtimes/rotate_token_mutation_spec.rb
  spec/requests/graphql/mutation/runtimes/update_mutation_spec.rb
  spec/services/runtimes/create_service_spec.rb
  spec/services/runtimes/delete_service_spec.rb
  spec/services/runtimes/rotate_token_service_spec.rb
  spec/services/runtimes/update_service_spec.rb
Labels: enhancement

#252 Initial start of grpc server implementation
  Gemfile
  Gemfile.lock
  app/grpc/concerns/grpc_handler.rb
  app/grpc/ping_handler.rb
  bin/grpc_server
  config/initializers/tucana.rb
  spec/grpc/ping_handler_spec.rb
Labels: enhancement

#273 Setup grpc testing and logging
  .rubocop.yml
  Gemfile
  Gemfile.lock
  bin/grpc_server
  config/initializers/logger.rb
  lib/sagittarius/grpc/launcher.rb
  lib/sagittarius/middleware/grpc/all_method_server_interceptor.rb
  lib/sagittarius/middleware/grpc/context.rb
  lib/sagittarius/middleware/grpc/logger.rb
  lib/sagittarius/utils.rb
  lib/tasks/statistics.rake
  spec/lib/sagittarius/middleware/grpc/logger_spec.rb
  spec/requests/grpc/internal/ping_service_spec.rb
  spec/spec_helper.rb
  spec/support/grpc_server.rb
  spec/support/helpers/grpc_helpers.rb
Labels: enhancement, tooling

#268 UserUpdate Mutation / Service
  app/graphql/mutations/users/update.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/user_type.rb
  app/models/audit_event.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/users/update_service.rb
  docs/content/graphql/mutation/usersupdate.md
  docs/content/graphql/object/user.md
  spec/graphql/mutations/users/update_spec.rb
  spec/graphql/types/user_type_spec.rb
  spec/requests/graphql/mutation/users/update_mutation_spec.rb
  spec/services/users/update_service_spec.rb
Labels: enhancement

#283 GRPC autentication
  config/application.rb
  lib/sagittarius/grpc/launcher.rb
  lib/sagittarius/middleware/grpc/authentication.rb
  spec/lib/sagittarius/middleware/grpc/authentication_spec.rb
  spec/requests/grpc/internal/ping_service_spec.rb
  spec/support/db_cleaner.rb
  spec/support/grpc_server.rb
  spec/support/helpers/grpc_helpers.rb
Labels: enhancement

#286 Setup pry debugger
  Gemfile
  Gemfile.lock
Labels: tooling

#258 implement user as a valid namespace
  app/graphql/types/user_type.rb
  app/models/namespace.rb
  app/models/user.rb
  app/policies/concerns/customizable_permission.rb
  app/policies/namespace_policy.rb
  app/services/namespace_members/assign_roles_service.rb
  app/services/namespace_members/delete_service.rb
  app/services/namespace_roles/assign_abilities_service.rb
  app/services/namespace_roles/delete_service.rb
  docs/content/graphql/object/user.md
  spec/factories/namespaces.rb
  spec/graphql/types/user_type_spec.rb
  spec/services/namespace_members/assign_roles_service_spec.rb
  spec/services/namespace_members/delete_service_spec.rb
  spec/services/namespace_roles/assign_abilities_service_spec.rb
Labels: enhancement

#287 Return a user session instead of a user on register service/mutation
  app/graphql/mutations/users/register.rb
  app/services/users/register_service.rb
  docs/content/graphql/mutation/usersregister.md
  spec/requests/graphql/mutation/users/register_spec.rb
  spec/services/users/register_service_spec.rb
Labels: enhancement
